# Generated by Django 2.2.6 on 2019-12-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('iscr_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'criteria',
            },
        ),
    ]
