# Generated by Django 2.2.6 on 2019-12-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191212_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
    ]
