# Generated by Django 2.2.6 on 2019-12-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
