# Generated by Django 2.2.6 on 2019-12-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191213_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='selection_result',
            field=models.CharField(max_length=500),
        ),
    ]
